#include "GA/GA_HitCheck.h"
#include "Character/PTPlayerCharacter.h"
#include "Abilities/Tasks/AbilityTask_WaitTargetData.h"
#include "TargetActor/PTTargetActorSphereTrace.h"

UGA_HitCheck::UGA_HitCheck()
{
}

void UGA_HitCheck::ActivateAbility(
	const FGameplayAbilitySpecHandle Handle,
	const FGameplayAbilityActorInfo* ActorInfo,
	const FGameplayAbilityActivationInfo ActivationInfo,
	const FGameplayEventData* TriggerEventData
)
{
	if (!HasAuthority(&ActivationInfo))
	{
		UE_LOG(LogTemp, Warning, TEXT("UGA_HitCheck::ActivateAbility - No Authority"));
		EndAbility(Handle, ActorInfo, ActivationInfo, true, false);
		return;
	}

	if (!CommitAbility(Handle, ActorInfo, ActivationInfo))
	{
		UE_LOG(LogTemp, Warning, TEXT("UGA_HitCheck::ActivateAbility - CommitAbility Failed"));
		EndAbility(Handle, ActorInfo, ActivationInfo, true, true);
		return;
	}

	UAbilityTask_WaitTargetData* Task =
		UAbilityTask_WaitTargetData::WaitTargetData(
			this,
			TEXT("HitCheckTask"),
			EGameplayTargetingConfirmation::Instant,
			APTTargetActorSphereTrace::StaticClass()
		);

	Task->ValidData.AddDynamic(this, &ThisClass::OnTargetDataReceived);
	Task->ReadyForActivation();

	AGameplayAbilityTargetActor* GenericActor = nullptr;
	if (Task->BeginSpawningActor(this, APTTargetActorSphereTrace::StaticClass(), GenericActor))
	{
		APTTargetActorSphereTrace* SpawnedActor = Cast<APTTargetActorSphereTrace>(GenericActor);
		if (SpawnedActor)
		{
			SpawnedActor->SetActorLocation(ActorInfo->AvatarActor->GetActorLocation());
		}

		Task->FinishSpawningActor(this, GenericActor);
	}
}

void UGA_HitCheck::EndAbility(
	const FGameplayAbilitySpecHandle Handle,
	const FGameplayAbilityActorInfo* ActorInfo,
	const FGameplayAbilityActivationInfo ActivationInfo,
	bool bReplicateEndAbility,
	bool bWasCancelled
)
{
	Super::EndAbility(Handle, ActorInfo, ActivationInfo, bReplicateEndAbility, bWasCancelled);
}

void UGA_HitCheck::OnTargetDataReceived(const FGameplayAbilityTargetDataHandle& DataHandle)
{
	TSet<APTPlayerCharacter*> UniqueTargets;
	for (int32 i = 0; i < DataHandle.Num(); ++i)
	{
		const FGameplayAbilityTargetData* Data = DataHandle.Get(i);

		if (const FGameplayAbilityTargetData_SingleTargetHit* HitData = static_cast<const FGameplayAbilityTargetData_SingleTargetHit*>(Data))
		{
			APTPlayerCharacter* HitActor = Cast<APTPlayerCharacter>(HitData->HitResult.GetActor());
			if (IsValid(HitActor))
			{
				UniqueTargets.Add(HitActor);
			}
		}
	}

	for (APTPlayerCharacter* HitCharacter : UniqueTargets)
	{
		HitCharacter->ServerRPCOnHit();
	}

	EndAbility(GetCurrentAbilitySpecHandle(), GetCurrentActorInfo(), GetCurrentActivationInfo(), true, false);
}

void UGA_HitCheck::OnTargetDataCancelled()
{
	EndAbility(CurrentSpecHandle, CurrentActorInfo, CurrentActivationInfo, false, false);
}
